/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Meee (https://sketchfab.com/Meee)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/earth-hologram-87072288fb234226b9a3f02ae674a310
title: Earth hologram
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
export function Earth1(props) {
  const meshRef = useRef(null);
  useFrame(() => (meshRef.current.rotation.z += 0.01));
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/earth1/scene.gltf");
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group
          color="#ff95ed"
          name="Sketchfab_model"
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.31}
        >
          <group name="Root">
            <group name="TERRE1" scale={3.27}>
              <mesh
                color="#ff95ed"
                //terre
                // ref={meshRef}
                name="TERRE1_0"
                geometry={nodes.TERRE1_0.geometry}
                material={materials["Material.005"]}
              />
            </group>
            <group name="Sphere002" rotation={[0, 0, -3.01]} scale={0.97}>
              <mesh
                color="#ff95ed"
                name="Sphere002_0"
                geometry={nodes.Sphere002_0.geometry}
                material={materials["Material.006"]}
              />
            </group>
            <group name="Circle643" scale={4.79}>
              <mesh
                color="#ff95ed"
                ref={meshRef}
                name="Circle643_0"
                geometry={nodes.Circle643_0.geometry}
                material={materials["Material.004"]}
              />
            </group>
            <group name="Circle455" scale={0.18}>
              <mesh
                color="#ff95ed"
                // asteroid
                // ref={meshRef}
                name="Circle455_0"
                geometry={nodes.Circle455_0.geometry}
                material={materials["Material.007"]}
                morphTargetDictionary={nodes.Circle455_0.morphTargetDictionary}
                morphTargetInfluences={nodes.Circle455_0.morphTargetInfluences}
              />
            </group>
            <group name="Circle" scale={6.13}>
              <group name="Icosphere002" position={[1, 0, 0]} scale={0.06}>
                <mesh
                  color="#ff95ed"
                  // ref={meshRef}
                  name="Icosphere002_0"
                  geometry={nodes.Icosphere002_0.geometry}
                  material={materials["Material.008"]}
                />
              </group>
              <mesh
                color="#ff95ed"
                //grand circle
                // ref={meshRef}
                name="Circle_0"
                geometry={nodes.Circle_0.geometry}
                material={materials["Material.010"]}
              />
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/scene.gltf");
